---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - learning.sagar
  resources:
  - learnings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - learning.sagar
  resources:
  - learnings/finalizers
  verbs:
  - update
- apiGroups:
  - learning.sagar
  resources:
  - learnings/status
  verbs:
  - get
  - patch
  - update
