apiVersion: learning.sagar/v1alpha1
kind: Learning
metadata:
  labels:
    app.kubernetes.io/name: learning
    app.kubernetes.io/instance: learning-sample
    app.kubernetes.io/part-of: k8soperatorlearning
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: k8soperatorlearning
  name: learning-sample-app
spec:
  # TODO(user): Add fields here
  appName: goLang
  nameSpace: go
  appContainerName: GoLangDemo
  appImage: sagar27/golangdemo
  appPort: 3000
  appReplica: 1
  mysqlDb: MYSQL_DATABASE
  vMysqlDb: db
  mysqlUser: MYSQL_USER
  vMysqlUser: root
  mysqlPassword: MYSQL_PASSWORD
  vMysqlPassword: password
  appDb: DBNAME
  vAppDb: golangdb
  dbHostName: HSTNAME
  vDbHostName: golang-0-dbdbsvc.go.svc.cluster.local
  service:
    name: gosvc
    namespace: go
    protocol: TCP
    targetPort: 3000
    nodePort: 30001
    type: NodePort