apiVersion: learning.sagar/v1alpha1
kind: Learning
metadata:
  labels:
    app.kubernetes.io/name: learning
    app.kubernetes.io/instance: learning-sample
    app.kubernetes.io/part-of: k8soperatorlearning
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: k8soperatorlearning
  name: learning-sample-db
spec:
  # TODO(user): Add fields here
  dbName: godb
  nameSpace: go
  dbContainerName: mysql
  dbImage: mysql:5.7
  dbPort: 3306
  dbVolumeName: mysql
  dbVolumePath: /var/lib/mysql
  dbVolumePvcName: mysql
  dbVolumeSize: 1Gi
  storageClassNameMysql: standard
  dbReplica: 1
  service:
    name: dbdbsvc
    namespace: go
    protocol: TCP
    port: 3306
    targetPort: 3306
    type: none